-- =====================================================================
-- SportFamilyRD - Datos de ejemplo (PostgreSQL)
-- =====================================================================
-- Requiere que database/schema.sql se haya ejecutado antes.
--
--   psql -d sportfamilyrd -f database/schema.sql
--   psql -d sportfamilyrd -f database/seed.sql
--
-- AVISO DE PRIVACIDAD
-- Este archivo contiene solo datos de catalogo (deportes y productos) y
-- usuarios inventados. No incluye usuarios reales, contraseñas, tokens de
-- acceso, mensajes ni publicaciones de la base de datos de produccion.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Usuarios de demostracion
-- La contraseña de los tres es: password
-- Cambiala antes de exponer este entorno en cualquier red.
-- ---------------------------------------------------------------------
INSERT INTO "users" ("id", "name", "email", "password", "user_type", "email_verified_at", "created_at", "updated_at") VALUES
    (1, 'Admin Demo', 'admin@sportfamilyrd.test', '$2y$10$fpqmE8Guh7rwe0ZuHAsrge2DkcAZmo.gZqw3Kuc2RkvnBp9l5mHNa', 'admin', NOW(), NOW(), NOW()),
    (2, 'Usuario Demo', 'usuario@sportfamilyrd.test', '$2y$10$fpqmE8Guh7rwe0ZuHAsrge2DkcAZmo.gZqw3Kuc2RkvnBp9l5mHNa', 'user', NOW(), NOW(), NOW()),
    (3, 'Entrenador Demo', 'entrenador@sportfamilyrd.test', '$2y$10$fpqmE8Guh7rwe0ZuHAsrge2DkcAZmo.gZqw3Kuc2RkvnBp9l5mHNa', 'trainer', NOW(), NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------
-- Catalogo de deportes (directorio)
-- ---------------------------------------------------------------------
INSERT INTO "sports" ("id", "name", "region", "type", "popularity", "image", "short_description", "description", "requirements", "places", "sort_order", "created_at", "updated_at") VALUES
    (1, 'Béisbol', 'Todo el país', 'Equipo', 'Muy popular', 'imagenes/DirectorioDeDeportes/baseball.jpg', 'Deporte nacional con gran legado en Grandes Ligas', 'El béisbol es considerado el deporte nacional de la República Dominicana, con una arraigada tradición que va desde las ligas infantiles hasta el circuito profesional de la LIDOM. Es fuente de identidad y orgullo nacional, además de ser el principal semillero de peloteros latinoamericanos en las Grandes Ligas de EE. UU. El país cuenta con academias afiliadas a equipos de MLB, así como con programas escolares y municipales que fomentan su práctica desde edades tempranas.', '["Guante de béisbol (según posición)", "Bate reglamentario (de madera o aluminio)", "Pelotas oficiales", "Zapatos con tacos", "Casco protector para bateo", "Uniforme deportivo (opcional en práctica informal)"]', '[{"cost": "Boletas RD$150 a RD$1 550 (según temporada y rival)", "name": "Estadio Quisqueya Juan Marichal", "website": "https://quisqueyajuanmarichal.com", "location": "Santo Domingo"}, {"cost": "Acceso privado (academias de formación afiliadas a equipos de MLB)", "name": "Academia de Béisbol MLB – Boca Chica", "location": "Boca Chica"}, {"cost": "Gratis (uso comunitario y ligas menores)", "name": "Campo de Béisbol Los Trinitarios", "location": "Santo Domingo Este"}, {"cost": "Gratis (ligas juveniles y torneos escolares)", "name": "Play Municipal de Esperanza", "location": "Valverde"}]', 0, '2026-08-25 20:07:10', '2026-08-25 20:07:10'),
    (2, 'Dominó', 'Todo el país', 'Parejas', 'Muy popular', 'imagenes/DirectorioDeDeportes/Domino.jpg', 'Juego de estrategia y tradición dominicana', 'El dominó es un juego de mesa profundamente arraigado en la vida social dominicana. Se practica principalmente en parques, colmados, clubes y centros comunitarios. Más que un pasatiempo, es un símbolo de convivencia intergeneracional y estrategia mental. La Federación Dominicana de Dominó organiza campeonatos nacionales, mientras que las asociaciones locales celebran torneos municipales y barriales, especialmente durante festividades.', '["Juego completo de 28 fichas (doble seis)", "Mesa o superficie plana", "4 jugadores (dos parejas enfrentadas)", "Lápiz y papel (opcional, para llevar puntuación) o Celular (para usar aplicaciones de dominó)"]', '[{"cost": "Gratis (mesas públicas al aire libre)", "name": "Parque Colón", "location": "Zona Colonial, Santo Domingo"}, {"cost": "RD$500 anuales (membresía de acceso y torneos)", "name": "Club de Dominó Santiago", "location": "Santiago de los Caballeros"}, {"cost": "Acceso con membresía del club (eventos internos y ligas sociales)", "name": "Club Naco", "location": "Santo Domingo"}, {"cost": "Gratis (mesas públicas, ambiente comunitario)", "name": "Parque Duarte", "location": "San Pedro de Macorís"}]', 1, '2026-08-25 20:07:10', '2026-08-25 20:07:10'),
    (3, 'Fútbol', 'Todo el país', 'Equipo', 'Muy popular', 'imagenes/DirectorioDeDeportes/Futbol.jpg', 'Deporte en expansión y motor de desarrollo juvenil', 'El fútbol ha crecido aceleradamente en popularidad, especialmente entre la juventud dominicana. Se practica en escuelas, clubes, ligas barriales y academias privadas. La creación de la Liga Dominicana de Fútbol (LDF) en 2015 marcó el inicio de su profesionalización. Desde entonces, el país ha incrementado su presencia en torneos internacionales, como la clasificación de la selección Sub-20 al Mundial de 2023 y a los Juegos Olímpicos de París 2024. Este crecimiento ha impulsado tanto la infraestructura como la formación de nuevos talentos a nivel nacional.', '["Balón de fútbol (talla 4 o 5, según la edad)", "Uniforme completo (camiseta, short y medias)", "Calzado con tacos o zapatillas adecuadas según la superficie", "Espinilleras (recomendadas)", "Conos, redes y vallas (para entrenamientos organizados)"]', '[{"cost": "Gratis (uso libre y torneos comunitarios)", "name": "Canchas comunitarias y escolares", "location": "Barrios y sectores de todo el país"}, {"cost": "Inscripciones desde RD$1 500 (cursos infantiles y juveniles)", "name": "Club Deportivo y Cultural Mauricio Báez", "location": "Villa Juana, Santo Domingo"}, {"cost": "Acceso gratuito para uso comunitario", "name": "Polideportivo de Invivienda", "location": "Santo Domingo Este"}, {"cost": "RD$2 500 mensuales (programa formativo)", "name": "Soccer Town SD", "location": "Santo Domingo"}, {"cost": "RD$3 500 mensuales (escuela privada de fútbol)", "name": "Barcelona Academy RD", "location": "Santo Domingo"}, {"cost": "RD$5 000 mensuales (modelo de formación FC Barcelona)", "name": "FCBEscola República Dominicana", "location": "Santiago"}]', 2, '2026-08-25 20:07:11', '2026-08-25 20:07:11'),
    (4, 'Windsurf y Kitesurf', 'Cabarete, Puerto Plata', 'Individual', 'Popular entre locales y turistas', 'imagenes/DirectorioDeDeportes/WindsurfyKitesurf.jpg', 'Capital caribeña de los deportes de viento', 'Cabarete, en la costa norte dominicana, es reconocido internacionalmente como un destino de clase mundial para windsurf y kitesurf. Sus condiciones únicas —vientos alisios constantes, arrecifes que moderan el oleaje y clima cálido todo el año— hacen que sea ideal tanto para principiantes como para profesionales. Escuelas certificadas por IKO ofrecen clases y alquiler de equipos con altos estándares de seguridad.', '["Tabla de windsurf o kitesurf con vela o cometa", "Arnés de seguridad", "Chaleco salvavidas o impacto", "Traje de neopreno (recomendado en invierno)"]', '[{"cost": "Clases desde RD$3 200 (sesión de 2 horas)", "name": "Kite Beach – Champion Kite School", "website": "https://championkite.com", "location": "Cabarete, Puerto Plata"}, {"cost": "Alquiler de equipo completo desde RD$4 000 por día", "name": "Vela Cabarete", "website": "https://velacabarete.com", "location": "Playa Cabarete, Puerto Plata"}]', 3, '2026-08-25 20:07:11', '2026-08-25 20:07:11'),
    (5, 'Sóftbol', 'Santo Domingo, Santiago y otras provincias', 'Equipo', 'Popular', 'imagenes/DirectorioDeDeportes/Sofbol.jpg', 'Versión accesible y recreativa del béisbol', 'El sóftbol es una variante del béisbol que se caracteriza por el uso de una pelota más grande y lanzamientos por debajo del hombro. Es ampliamente practicado en ligas empresariales, universitarias y municipales. La Federación Dominicana de Sóftbol organiza torneos nacionales y promueve el desarrollo juvenil y femenino. Su ambiente competitivo pero recreativo lo hace ideal para todas las edades.', '["Guante de sóftbol", "Bate de sóftbol", "Pelota oficial de sóftbol", "Zapatos con tacos o suela adecuada"]', '[{"cost": "Entrenamiento gratuito (ligas federadas desde RD$1 500 por temporada)", "name": "Campo de Sóftbol del Centro Olímpico Juan Pablo Duarte", "location": "Santo Domingo"}, {"cost": "Gratis (uso comunitario, ligas barriales)", "name": "Play Los Mameyes", "location": "Santo Domingo Este"}, {"cost": "Gratis o bajo costo según liga local", "name": "Play de Sóftbol de Gurabo", "location": "Santiago"}]', 4, '2026-08-25 20:07:11', '2026-08-25 20:07:11'),
    (6, 'Pesca Deportiva', 'La Romana, Samaná, Punta Cana', 'Individual/Grupo', 'Media', 'imagenes/DirectorioDeDeportes/Pesca.jpg', 'Pesca en alta mar de especies como marlín, dorado y atún', 'La pesca deportiva en República Dominicana se concentra en sus costas orientales y del norte, siendo un destino destacado en el Caribe. Se realizan torneos de prestigio como el Torneo Internacional de Marlín Blanco en La Romana. Las especies más buscadas incluyen el marlín azul, el pez vela y el atún. La temporada alta va de junio a septiembre, y es común practicarla mediante excursiones organizadas o embarcaciones privadas.', '["Caña y carrete de pesca de agua salada (saltwater)", "Arnés y cinturón de pelea para pesca de gran tamaño", "Licencia de pesca (requerida en torneos oficiales)", "Chaleco salvavidas (obligatorio en embarcaciones)"]', '[{"cost": "Charters privados desde RD$15 000 por jornada", "name": "Marina Casa de Campo", "website": "https://www.casadecampo.com.do", "location": "La Romana"}, {"cost": "Excursión compartida desde RD$12 000 por persona", "name": "Excursiones Samaná Fishing", "location": "Samaná"}, {"cost": "Salidas de medio día desde RD$10 000", "name": "Ocean Adventures Punta Cana", "location": "Punta Cana"}]', 5, '2026-08-25 20:07:11', '2026-08-25 20:07:11'),
    (7, 'Baloncesto', 'Santo Domingo, Santiago, San Pedro de Macorís', 'Equipo', 'Muy popular', 'imagenes/DirectorioDeDeportes/Baloncesto.jpg', 'Canastas en cada barrio dominicano', 'El baloncesto es uno de los deportes más practicados en la República Dominicana, especialmente entre jóvenes de zonas urbanas. Cuenta con fuerte presencia en ligas escolares, universitarias y municipales. La Liga Nacional de Baloncesto (LNB), fundada en 2005, es la principal competición profesional del país. La selección nacional ha obtenido importantes logros en Centrobasket y Juegos Centroamericanos. La influencia de la NBA se refleja en la afición y el estilo de juego local.', '["Balón oficial de baloncesto (talla 7 para varones, talla 6 para mujeres)", "Zapatillas deportivas de suela media o alta", "Ropa deportiva cómoda (camiseta y pantalón corto)", "Cancha con tableros y aros reglamentarios"]', '[{"cost": "Boletas desde RD$200 (eventos oficiales)", "name": "Palacio de los Deportes Virgilio Travieso Soto", "location": "Centro Olímpico Juan Pablo Duarte, Santo Domingo"}, {"cost": "Acceso gratuito (uso libre diario)", "name": "Canchas abiertas del Parque Mirador Sur", "location": "Santo Domingo"}, {"cost": "Programas juveniles desde RD$1 000 mensuales", "name": "Club San Carlos", "location": "Distrito Nacional"}, {"cost": "Entrada libre para entrenamientos comunitarios", "name": "Multiuso de Los Pepines", "location": "Santiago"}]', 6, '2026-08-25 20:07:11', '2026-08-25 20:07:11'),
    (8, 'Voleibol', 'Todo el país (playas y clubes)', 'Equipo', 'Muy popular', 'imagenes/DirectorioDeDeportes/Volleyball.jpg', 'Tradición olímpica y éxito internacional', 'El voleibol es uno de los deportes colectivos más exitosos de la República Dominicana, especialmente en su modalidad femenina. La selección nacional ha ganado múltiples medallas de oro en los Juegos Panamericanos (2003, 2019, 2023) y es considerada una potencia en NORCECA. Se practica ampliamente tanto en canchas de sala como en playas caribeñas. El voleibol de playa es muy popular en torneos veraniegos y en el circuito juvenil. El país cuenta con una sólida infraestructura de clubes, ligas y entrenadores.', '["Balón de voleibol (interior o playa)", "Red de vóley (ajustada según tipo de superficie)", "Zapatillas deportivas (o pies descalzos en la arena)", "Ropa deportiva cómoda"]', '[{"cost": "Gratis (torneos veraniegos y uso libre)", "name": "Playa Boca Chica (cancha pública de vóley)", "location": "Boca Chica, Santo Domingo Este"}, {"cost": "RD$500 por sesión de entrenamiento", "name": "Pabellón de Voleibol – Centro Olímpico", "location": "Santo Domingo"}, {"cost": "Membresía o pago por clases (~RD$2 000 mensuales)", "name": "Club Deportivo Naco", "location": "Santo Domingo"}, {"cost": "Acceso libre (torneos organizados en verano)", "name": "Playa Juan Dolio", "location": "San Pedro de Macorís"}]', 7, '2026-08-25 20:07:11', '2026-08-25 20:07:11'),
    (9, 'Atletismo', 'Santo Domingo y otras ciudades', 'Individual', 'Media', 'imagenes/DirectorioDeDeportes/Atletismo.jpg', 'Cuna de medallistas olímpicos dominicanos', 'El atletismo en la República Dominicana cuenta con un legado olímpico, encabezado por Félix Sánchez, doble medallista de oro en 400 m vallas. El país dispone de pistas profesionales abiertas al público y circuitos urbanos para corredores de fondo y velocidad. Es una disciplina clave para el desarrollo físico juvenil, con programas de iniciación y clubes escolares. La práctica recreativa es común en parques y avenidas habilitadas, especialmente en Santo Domingo.', '["Zapatillas de correr o spike según especialidad", "Ropa deportiva ligera", "Cronómetro o reloj deportivo (opcional)", "Botella de agua e hidratación"]', '[{"cost": "Acceso libre en horarios no federados", "name": "Pista Félix Sánchez – Centro Olímpico Juan Pablo Duarte", "location": "Santo Domingo"}, {"cost": "Gratis (circuito urbano de 5 km, bien iluminado)", "name": "Avenida de la Salud (Mirador Sur)", "location": "Santo Domingo"}, {"cost": "Acceso libre (entrenamientos comunitarios)", "name": "Pista de Atletismo del Polideportivo", "location": "La Vega"}, {"cost": "Gratis (espacios señalizados para correr y caminar)", "name": "Parque Central de Santiago", "location": "Santiago de los Caballeros"}]', 8, '2026-08-25 20:07:12', '2026-08-25 20:07:12'),
    (10, 'Boxeo', 'Santo Domingo, San Cristóbal y otras provincias', 'Individual', 'Alta', 'imagenes/DirectorioDeDeportes/Boxeo.jpg', 'Cuna de campeones mundiales y olímpicos', 'El boxeo dominicano tiene una rica tradición que ha producido figuras como Carlos "Teo" Cruz, Joan Guzmán y el medallista olímpico Félix Díaz. Es uno de los deportes con mayor impacto social, especialmente en sectores populares. Gimnasios públicos y federativos ofrecen entrenamiento gratuito a niños, jóvenes y adultos, fomentando la disciplina, la autodefensa y la proyección atlética. Las competencias incluyen torneos nacionales, municipales y eventos internacionales con representación oficial.', '["Guantes de boxeo homologados", "Vendas para manos", "Protector bucal", "Ropa deportiva (short y camiseta sin mangas)", "Casco y careta (para entrenamientos amateur)"]', '[{"cost": "Gratis (programas de MIDEREC y Federación Dominicana de Boxeo)", "name": "Gimnasio Nacional de Boxeo – Centro Olímpico", "location": "Santo Domingo"}, {"cost": "Entrenamiento gratuito para jóvenes comunitarios", "name": "Gimnasio Municipal de Boxeo", "location": "San Cristóbal"}, {"cost": "Clases federadas a bajo costo (desde RD$500/mes)", "name": "Club Mauricio Báez", "location": "Villa Juana, Santo Domingo"}]', 9, '2026-08-25 20:07:12', '2026-08-25 20:07:12'),
    (11, 'Golf', 'Punta Cana, La Romana y zonas turísticas', 'Individual', 'Media‑Alta', 'imagenes/DirectorioDeDeportes/Golf.jpg', 'Campos de clase mundial frente al mar Caribe', 'La República Dominicana es considerada el principal destino de golf en el Caribe. Cuenta con más de 25 campos de nivel internacional, muchos de ellos diseñados por leyendas como Jack Nicklaus, Pete Dye y Tom Fazio. Punta Espada (Cap Cana) y Teeth of the Dog (Casa de Campo) figuran entre los mejores del hemisferio occidental según rankings especializados. Estos campos combinan desafíos técnicos con vistas espectaculares al mar, atrayendo tanto a golfistas profesionales como a turistas amateurs.', '["Juego completo de palos de golf", "Bolas oficiales de golf", "Zapatos con suela soft spikes", "Guante (opcional pero recomendado)", "Vestimenta formal de golf (polo, pantalón largo o bermuda)"]', '[{"cost": "Green fee desde RD$8 000", "name": "Punta Espada Golf Club", "website": "https://puntaspadagolfclub.com", "location": "Cap Cana, Punta Cana"}, {"cost": "Green fee desde RD$6 500", "name": "Teeth of the Dog – Casa de Campo", "website": "https://www.casadecampo.com.do/golf/teeth-of-the-dog/", "location": "La Romana"}, {"cost": "Desde RD$4 000 (green fee diario)", "name": "Playa Dorada Golf Course", "website": "https://playadoradagolf.com", "location": "Puerto Plata"}]', 10, '2026-08-25 20:07:12', '2026-08-25 20:07:12'),
    (12, 'Surf', 'Costa norte (Puerto Plata, Cabarete, Macao)', 'Individual', 'Creciente', 'imagenes/DirectorioDeDeportes/Surf.jpg', 'Olas todo el año en la costa norte dominicana', 'El surf en la República Dominicana ha ganado notoriedad internacional gracias a las condiciones ideales de la costa norte. Playa Encuentro, cerca de Cabarete, es considerada la cuna del surf dominicano por sus rompientes consistentes aptas para todos los niveles. Además, playas como Macao (Punta Cana) y El Barco (Puerto Plata) ofrecen escenarios ideales para la práctica recreativa y competitiva. Escuelas certificadas imparten clases con instructores profesionales y alquilan equipos.', '["Tabla de surf adecuada al nivel (shortboard o longboard)", "Leash (soga de seguridad)", "Rashguard o traje de neopreno (según temporada)", "Cera para tabla (wax)", "Bloqueador solar resistente al agua"]', '[{"cost": "Clases desde RD$2 800 por 2 horas", "name": "Cabarete Surf Company", "website": "https://cabaretesurf.com", "location": "Playa Encuentro, Puerto Plata"}, {"cost": "Clase individual desde RD$3 000", "name": "Macao Surf Camp", "website": "https://macaosurfcamp.com", "location": "Playa Macao, Punta Cana"}, {"cost": "Clases desde RD$2 500", "name": "Dominican Surf School", "website": "https://dominicansurfschool.com", "location": "Playa El Barco, Puerto Plata"}]', 11, '2026-08-25 20:07:12', '2026-08-25 20:07:12'),
    (13, 'Tenis', 'Santo Domingo, Santiago, La Romana', 'Individual/Parejas', 'Media', 'imagenes/DirectorioDeDeportes/Tenis.jpg', 'Canchas profesionales y academias en crecimiento', 'El tenis en República Dominicana se practica principalmente en clubes privados y centros deportivos de alto nivel. La Federación Dominicana de Tenis organiza torneos federados (Futures ITF, Challenger ATP y torneos juveniles nacionales). Clubes como “La Bocha” y el Centro Nacional de Tenis impulsan la formación de atletas desde edades tempranas. La infraestructura incluye canchas de arcilla y superficie dura, con iluminación y entrenadores certificados.', '["Raqueta de tenis (acorde al nivel)", "Pelotas oficiales", "Zapatillas específicas para tenis (arcilla o hard court)", "Toalla y botella de hidratación"]', '[{"cost": "RD$300–1 000/h (alquiler para invitados)", "name": "Santo Domingo Tennis Club “La Bocha”", "website": "http://labocha.org", "location": "Santo Domingo"}, {"cost": "Clases y acceso desde RD$500/sesión", "name": "Centro Nacional de Tenis (FEDOTENIS)", "website": "https://fedotenis.com.do", "location": "Parque del Este, Santo Domingo Este"}, {"cost": "RD$400–800 por hora (alquiler de cancha)", "name": "Club de Tenis Caribe", "website": "https://clubteniscaribe.com", "location": "Santiago de los Caballeros"}]', 12, '2026-08-25 20:07:12', '2026-08-25 20:07:12'),
    (14, 'Ciclismo', 'Jarabacoa, Constanza, Santo Domingo, Santiago', 'Individual/Grupo', 'Media', 'imagenes/DirectorioDeDeportes/Ciclismo.jpg', 'Montaña y carretera en paisajes caribeños', 'El ciclismo dominicano combina rutas de alta montaña y tramos urbanos. La Cordillera Central ofrece desafíos como la ruta Jarabacoa–Constanza, considerada una de las más exigentes y bellas del Caribe. La Vuelta Ciclística Independencia (febrero) es la principal competencia profesional del país. Cada vez más ciclistas recreativos y clubes organizan salidas los fines de semana en todo el territorio.', '["Bicicleta de montaña o ruta en buen estado", "Casco obligatorio", "Kit de reparación básico (cámara, inflador, parches)", "Botella de hidratación y gafas solares"]', '[{"cost": "Gratis (ruta escénica de ~60 km con puertos altos)", "name": "Ruta Jarabacoa – Constanza (La Vega – El Río)", "location": "Cordillera Central"}, {"cost": "Gratis (uso libre domingos y festivos)", "name": "Ciclovía Mirador Sur", "location": "Santo Domingo"}, {"cost": "Gratis (ruta de montaña; ideal MTB o gravel)", "name": "Valle Nuevo – La Pirámide", "location": "Constanza"}]', 13, '2026-08-25 20:07:13', '2026-08-25 20:07:13'),
    (15, 'Judo', 'Santo Domingo y Santiago', 'Individual', 'Media', 'imagenes/DirectorioDeDeportes/Judo.jpg', 'Disciplina olímpica de respeto y control', 'El judo dominicano se desarrolla bajo normas de la Federación Internacional de Judo. Se practica desde edades tempranas en dojos certificados, combinando técnica, táctica y valores como la cortesía, autocontrol y esfuerzo. La selección nacional ha representado a RD en eventos como los Juegos Panamericanos y Centroamericanos, con proyección internacional.', '["Judogi (traje oficial de judo)", "Cinturón correspondiente al grado", "Protección bucal (opcional)", "Botella de agua y toalla personal"]', '[{"cost": "RD$1 500/mes (membresía federativa)", "name": "Dojo Nacional de Judo – Centro Olímpico", "website": "https://fedorjudo.org.do", "location": "Santo Domingo"}, {"cost": "Entrenamientos desde RD$1 200/mes", "name": "Dojo Regional de Santiago – Complejo Deportivo La Barranquita", "location": "Santiago de los Caballeros"}]', 14, '2026-08-25 20:07:13', '2026-08-25 20:07:13'),
    (16, 'Equitación', 'Santo Domingo, Bonao', 'Individual', 'Media', 'imagenes/DirectorioDeDeportes/Equitacion.jpg', 'Montura, salto y elegancia ecuestre', 'La equitación combina destreza técnica y conexión con el caballo. En República Dominicana se practica salto ecuestre, doma clásica y equitación recreativa. Los clubes hípicos ofrecen clases para niños y adultos, además de competencias locales los fines de semana. Es un deporte que fomenta disciplina, control corporal y cuidado animal.', '["Casco homologado de equitación", "Botas y pantalones de montar", "Chaleco protector (recomendado)", "Licencia federativa (para competencia)"]', '[{"cost": "Clase individual desde RD$2 000", "name": "Club Hípico Santo Domingo", "website": "https://clubhipico.com.do", "location": "Santo Domingo"}, {"cost": "Clases y cabalgatas guiadas desde RD$1 800", "name": "Club Ecuestre de Bonao", "location": "Bonao"}]', 15, '2026-08-25 20:07:13', '2026-08-25 20:07:13'),
    (17, 'Karate', 'Todo el país', 'Individual', 'Media‑Alta', 'imagenes/DirectorioDeDeportes/Karate.jpg', 'Disciplina marcial de formación integral', 'El karate es una de las artes marciales más practicadas en el país, con cientos de dojos afiliados a la Federación Dominicana de Karate. Forma parte del programa deportivo escolar y universitario, y ha aportado medallistas internacionales en categorías juveniles y adultas. La práctica combina defensa personal, kata (formas) y kumite (combate).', '["Karategi (uniforme reglamentario)", "Cinturón (según grado)", "Protecciones (guantes, bucal, espinilleras)", "Licencia federativa (en competencias)"]', '[{"cost": "Desde RD$1 200/mes", "name": "Dojo Central – Federación Dominicana de Karate", "website": "https://fedokarate.org", "location": "Centro Olímpico, Santo Domingo"}, {"cost": "RD$1 000–2 000 mensuales (según dojo)", "name": "Dojos privados y comunitarios", "location": "Santiago, San Cristóbal, La Vega, San Juan…"}]', 16, '2026-08-25 20:07:13', '2026-08-25 20:07:13'),
    (18, 'Buceo', 'Bayahibe, Sosúa, Punta Cana', 'Individual/Grupo', 'Alta en zonas turísticas', 'imagenes/DirectorioDeDeportes/Buceo.jpg', 'Arrecifes, naufragios y vida marina del Caribe', 'El buceo en República Dominicana ofrece inmersiones en arrecifes coralinos, cuevas submarinas y pecios históricos. Bayahibe es la principal base de exploración, con acceso al Parque Nacional Cotubanamá y naufragios como el “Saint George”. También destacan las aguas de Sosúa y Punta Cana. Centros certificados PADI imparten formación desde principiantes (Discover Scuba) hasta niveles profesionales.', '["Certificación PADI (obligatoria para inmersiones >12 m)", "Equipo completo de buceo (tanque, regulador, máscara, aletas)", "Opción de alquiler en centros locales", "Buen estado físico y saber nadar"]', '[{"cost": "Inmersión guiada desde RD$4 500", "name": "Coral Point Diving", "website": "https://coralpointdiving.com", "location": "Bayahibe, La Romana"}, {"cost": "Tour de buceo en arrecifes y pecios desde RD$4 000", "name": "Ocean Adventures", "website": "https://oceanadventures-puntacana.com", "location": "Punta Cana"}, {"cost": "Buceo en arrecifes desde RD$3 000", "name": "Sosúa Diving Center", "website": "https://sosuadivingcenter.com", "location": "Sosúa, Puerto Plata"}]', 17, '2026-08-25 20:07:13', '2026-08-25 20:07:13'),
    (19, 'Parapente', 'Constanza y Jarabacoa', 'Individual', 'Emergente', 'imagenes/DirectorioDeDeportes/Parapente.jpg', 'Vuelos panorámicos sobre montañas y valles', 'El parapente es una experiencia de vuelo libre que gana popularidad en las zonas montañosas de RD. Jarabacoa y Constanza ofrecen condiciones óptimas durante todo el año gracias a sus vientos térmicos suaves. Escuelas certificadas organizan vuelos tándem con pilotos expertos, ideales tanto para principiantes como para aventureros.', '["Arnés y vela certificada para parapente", "Casco protector", "Paracaídas de emergencia (incluido en vuelos tándem)", "Ropa deportiva cómoda y abrigada"]', '[{"cost": "Vuelo tándem RD$6 000 por persona", "name": "EcoParapente RD", "website": "https://ecoparapenterd.com", "location": "Jarabacoa, La Vega"}, {"cost": "Vuelo panorámico desde RD$6 000", "name": "Parapente RD", "website": "https://parapenterd.com", "location": "Constanza, La Vega"}]', 18, '2026-08-25 20:07:13', '2026-08-25 20:07:13'),
    (20, 'Yaque Rafting', 'Jarabacoa', 'Grupo', 'Alta en temporada', 'imagenes/DirectorioDeDeportes/YaqueRafting.jpg', 'Aventura acuática en rápidos caribeños', 'El rafting en el río Yaque del Norte, el más extenso del Caribe, combina adrenalina y paisajes montañosos. Con rápidos clase II a IV, es ideal tanto para principiantes como para amantes de la aventura. Las excursiones incluyen instrucción técnica y acompañamiento de guías certificados, con salida desde La Confluencia y descenso hasta Jima Abajo.', '["Chaleco salvavidas aprobado", "Casco de protección", "Remo personal", "Ropa impermeable o de secado rápido", "Saber nadar (recomendado)"]', '[{"cost": "Paquete completo RD$3 500 (incluye equipo y transporte)", "name": "Rancho Baiguate", "website": "https://ranchobaiguate.com", "location": "Jarabacoa"}]', 19, '2026-08-25 20:07:14', '2026-08-25 20:07:14'),
    (21, 'Carreras de Caballos', 'Santo Domingo, Santiago', 'Individual', 'Tradicional', 'imagenes/DirectorioDeDeportes/CarreraDeCaballos.jpg', 'Tradición ecuestre y adrenalina en la pista', 'Las carreras de caballos forman parte del patrimonio deportivo dominicano. El Hipódromo V Centenario es el recinto oficial, con eventos todos los fines de semana y apuestas reguladas. En zonas rurales también se celebran carreras informales y tradicionales, como las “cintas”, durante fiestas patronales.', '["Caballo registrado en asociación ecuestre", "Jinete profesional o aprendiz licenciado", "Inscripción previa en la carrera", "Equipo de monta homologado"]', '[{"cost": "Entrada general RD$200 (eventos sabatinos)", "name": "Hipódromo V Centenario", "website": "https://hipodromord.com", "location": "Santo Domingo"}, {"cost": "Variable (según competencia y acceso)", "name": "Hipódromo Real", "location": "Santiago (eventos ocasionales)"}]', 20, '2026-08-25 20:07:14', '2026-08-25 20:07:14'),
    (22, 'Tiro Deportivo', 'Santo Domingo, Santiago', 'Individual', 'Media', 'imagenes/DirectorioDeDeportes/TiroDeportivo.jpg', 'Disciplina de precisión bajo normativa internacional', 'El tiro deportivo en República Dominicana se practica en clubes federados bajo las normas de la ISSF. Incluye modalidades con pistola, rifle y escopeta en distancias de 10, 25 y 50 metros. Es una disciplina que exige control, seguridad y concentración, con campeonatos nacionales organizados por la Federación Dominicana de Tiro.', '["Arma deportiva registrada (pistola, rifle o escopeta según modalidad)", "Protección auditiva y ocular", "Licencia de tirador federado", "Conocimiento y cumplimiento de normas de seguridad"]', '[{"cost": "RD$1 500 por sesión de práctica", "name": "Club de Tiro Santo Domingo", "website": "https://clubtiro.com.do", "location": "Santo Domingo Este"}, {"cost": "RD$1 000–1 800 (según modalidad y nivel)", "name": "Academia de Tiro Santiago", "location": "Santiago de los Caballeros"}]', 21, '2026-08-25 20:07:14', '2026-08-25 20:07:14'),
    (23, 'Yoga en Playa', 'Punta Cana, Cabarete, Las Terrenas', 'Individual/Grupo', 'Creciente', 'imagenes/DirectorioDeDeportes/YogaEnPlaya.jpg', 'Bienestar físico y mental frente al mar', 'La práctica de yoga al aire libre ha ganado popularidad en destinos turísticos costeros. Las clases en playa combinan posturas de hatha o vinyasa con técnicas de respiración consciente y meditación, especialmente al amanecer o al atardecer. Es ideal para reducir el estrés y conectar con la naturaleza en un entorno caribeño.', '["Mat antideslizante (colchoneta)", "Ropa cómoda y transpirable", "Bloques o correas (opcional para nivel principiante)", "Hidratación adecuada"]', '[{"cost": "Clase grupal RD$800", "name": "Yoga Punta Cana", "website": "https://yogapuntacana.com", "location": "Playa Bávaro, Punta Cana"}, {"cost": "Sesiones al atardecer RD$700–1 000 (según duración)", "name": "Bahía Yoga", "location": "Playa Bonita, Las Terrenas"}]', 22, '2026-08-25 20:07:14', '2026-08-25 20:07:14'),
    (24, 'Pádel', 'Santo Domingo, Punta Cana', 'Parejas', 'Emergente', 'imagenes/DirectorioDeDeportes/Padel.jpg', 'Raqueta, estrategia y dinamismo en cancha cerrada', 'El pádel es un deporte de raqueta que se juega en parejas dentro de una cancha cerrada con paredes de cristal. Su popularidad ha crecido rápidamente en República Dominicana desde 2020, impulsada por la construcción de canchas en clubes sociales y gimnasios. La Federación Dominicana de Pádel organiza torneos oficiales y circuitos nacionales, atrayendo tanto a jugadores recreativos como competitivos.', '["Pala de pádel (sin cuerdas)", "Pelotas presurizadas específicas", "Zapatillas de pádel o tenis con suela apropiada", "Ropa deportiva ligera"]', '[{"cost": "Alquiler de cancha RD$1 200/hora", "name": "Padel Center SD", "website": "https://padelcenterrd.com", "location": "Santo Domingo"}, {"cost": "Canchas dobles disponibles (desde RD$1 000/hora)", "name": "Centro Deportivo Punta Cana", "location": "Punta Cana"}]', 23, '2026-08-25 20:07:14', '2026-08-25 20:07:14'),
    (25, 'Ultimate Frisbee', 'Santo Domingo, Santiago', 'Equipo', 'Emergente', 'imagenes/DirectorioDeDeportes/UltimateFrisbee.jpg', 'Disciplina sin árbitros basada en el juego limpio', 'El Ultimate Frisbee es un deporte colectivo sin contacto físico y sin árbitros, que promueve el “espíritu de juego”. En República Dominicana, se practica en entornos universitarios y comunitarios desde 2005. Ligas como la Santo Domingo Ultimate League (SDUL) y clubes en INTEC y PUCMM organizan torneos y encuentros regulares. Es una disciplina que combina velocidad, resistencia, trabajo en equipo y estrategia.', '["Disco oficial de 175 g (reglamentario)", "Conos para delimitar el campo de juego", "Zapatillas deportivas adecuadas para césped o tierra"]', '[{"cost": "Gratis (uso abierto)", "name": "Parque Mirador Sur – campo central", "location": "Santo Domingo"}, {"cost": "Acceso universitario o con permiso previo", "name": "Campus INTEC y PUCMM", "location": "Santo Domingo y Santiago"}]', 24, '2026-08-25 20:07:14', '2026-08-25 20:07:14')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------
-- Catalogo de productos (tienda)
-- ---------------------------------------------------------------------
INSERT INTO "products" ("id", "name", "description", "stock", "price", "category", "image", "created_at", "updated_at") VALUES
    (1, 'Balón de Fútbol Profesional', 'Balón de fútbol tamaño oficial, cosido a mano, ideal para césped natural y sintético.', 40, '1450.00', 'Futbol', 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:16', '2026-08-25 18:52:16'),
    (2, 'Balón de Baloncesto Oficial', 'Balón de baloncesto tamaño 7, superficie de goma para exteriores.', 35, '1650.00', 'Baloncesto', 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:17', '2026-08-25 18:52:17'),
    (3, 'Raqueta de Tenis Pro', 'Raqueta de tenis de grafito, peso ligero, ideal para jugadores intermedios y avanzados.', 20, '4200.00', 'Tenis', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:17', '2026-08-25 18:52:17'),
    (4, 'Bicicleta de Ruta Aluminio', 'Bicicleta de ruta cuadro de aluminio, 21 velocidades, frenos de disco.', 8, '28500.00', 'Ciclismo', 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:17', '2026-08-25 18:52:17'),
    (5, 'Gafas de Natación Antiempañantes', 'Gafas de natación con protección UV y sello de silicona hipoalergénico.', 50, '850.00', 'Natacion', 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:17', '2026-08-25 18:52:17'),
    (6, 'Camiseta Deportiva Dry-Fit Hombre', 'Camiseta transpirable de secado rápido, ideal para entrenamientos intensos.', 60, '950.00', 'Hombres', 'https://images.unsplash.com/photo-1562088287-bde35a1ea917?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:17', '2026-08-25 18:52:17'),
    (7, 'Leggings Deportivos Mujer', 'Leggings de alta compresión con cintura ancha, tela elástica que no transparenta.', 55, '1100.00', 'Mujeres', 'https://images.unsplash.com/photo-1596357395217-80de13130e92?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:17', '2026-08-25 18:52:17'),
    (8, 'Conjunto Deportivo Infantil', 'Conjunto de camiseta y short deportivo para niños, tela ligera y resistente.', 30, '780.00', 'Ninos', 'https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:18', '2026-08-25 18:52:18'),
    (9, 'Tenis para Correr', 'Zapatillas running con amortiguación de espuma y suela antideslizante.', 45, '3200.00', 'Calzado', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:18', '2026-08-25 18:52:18'),
    (10, 'Chaqueta Cortavientos Activewear', 'Chaqueta ligera resistente al viento, ideal para trotar en clima fresco.', 25, '2100.00', 'Activewear', 'https://images.unsplash.com/photo-1550345332-09e3ac987658?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:18', '2026-08-25 18:52:18'),
    (11, 'Set de Pelotas de Tenis (3 unidades)', 'Set de 3 pelotas de tenis de competencia, alta durabilidad.', 70, '550.00', 'Pelotas', 'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:18', '2026-08-25 18:52:18'),
    (12, 'Raqueta de Bádminton', 'Raqueta de bádminton de aluminio, liviana y resistente.', 22, '1350.00', 'Raquetas', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:18', '2026-08-25 18:52:18'),
    (13, 'Bicicleta de Montaña Rin 29', 'Bicicleta MTB rin 29, suspensión delantera, 24 velocidades.', 6, '32000.00', 'Bicicletas', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:19', '2026-08-25 18:52:19'),
    (14, 'Set de Mancuernas Ajustables', 'Par de mancuernas ajustables de 5 a 25 kg, ideales para entrenar en casa.', 15, '6800.00', 'Pesas', 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:19', '2026-08-25 18:52:19'),
    (15, 'Rodilleras de Protección Deportiva', 'Par de rodilleras acolchadas para baloncesto, voleibol y deportes de contacto.', 40, '680.00', 'Protecciones', 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:19', '2026-08-25 18:52:19'),
    (16, 'Proteína Whey 2 lb', 'Proteína de suero de leche sabor chocolate, 24g de proteína por porción.', 50, '2800.00', 'Proteinas', 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:19', '2026-08-25 18:52:19'),
    (17, 'Multivitamínico Deportivo', 'Complejo multivitamínico formulado para deportistas, 60 tabletas.', 65, '950.00', 'Vitaminas', 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:19', '2026-08-25 18:52:19'),
    (18, 'Quemador de Grasa Termogénico', 'Suplemento termogénico para apoyar la pérdida de grasa, 60 cápsulas.', 38, '1800.00', 'Quemadores', 'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:20', '2026-08-25 18:52:20'),
    (19, 'Bebida Energizante Pre-Entreno', 'Fórmula pre-entreno con cafeína y beta-alanina, sabor frutas rojas.', 42, '1600.00', 'Energizantes', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:20', '2026-08-25 18:52:20'),
    (20, 'Barras de Proteína (Caja x12)', 'Caja de 12 barras de proteína sabor maní y chocolate, 15g de proteína cada una.', 28, '1400.00', 'Barras', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&auto=format&fit=crop&q=80', '2026-08-25 18:52:20', '2026-08-25 18:52:20'),
    (21, 'Smartwatch Deportivo con GPS', 'Reloj deportivo con monitor de ritmo cardíaco, GPS y resistencia al agua.', 18, '5200.00', 'Electrónicos', 'https://images.unsplash.com/photo-1550345332-09e3ac987658?w=700&auto=format&fit=crop&q=80', '2026-08-25 18:52:20', '2026-08-25 18:52:20'),
    (22, 'Botella Térmica Deportiva 1L', 'Botella de acero inoxidable, mantiene la temperatura hasta 12 horas.', 60, '620.00', 'Hidratación', 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=700&auto=format&fit=crop&q=80', '2026-08-25 18:52:20', '2026-08-25 18:52:20'),
    (23, 'Mochila Deportiva Impermeable', 'Mochila con compartimento para tenis y bolsillo térmico, resistente al agua.', 24, '1750.00', 'Mochilas', 'https://images.unsplash.com/photo-1596357395217-80de13130e92?w=700&auto=format&fit=crop&q=80', '2026-08-25 18:52:20', '2026-08-25 18:52:20'),
    (24, 'Reloj Deportivo Resistente al Agua', 'Reloj digital deportivo con cronómetro y resistencia al agua hasta 50m.', 30, '1200.00', 'Relojes', 'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=700&auto=format&fit=crop&q=80', '2026-08-25 18:52:21', '2026-08-25 18:52:21'),
    (25, 'Toalla Deportiva de Microfibra', 'Toalla de microfibra de secado rápido, ideal para gimnasio y natación.', 80, '380.00', 'Toallas', 'https://images.unsplash.com/photo-1562088287-bde35a1ea917?w=700&auto=format&fit=crop&q=80', '2026-08-25 18:52:21', '2026-08-25 18:52:21')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------
-- Resincronizar las secuencias
-- Al insertar ids explicitos la secuencia no avanza. Sin este paso, el
-- primer registro que cree la aplicacion chocaria con un id existente.
-- ---------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM "users"), 1));
SELECT setval(pg_get_serial_sequence('sports', 'id'), COALESCE((SELECT MAX(id) FROM "sports"), 1));
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM "products"), 1));

COMMIT;
